hash-format = "sha256"

[[files]]
file = "mods/alexs-caves.pw.toml"
hash = "61b6b90ed30ec8cee04ad19584438f89656532c4e54ff2f47cf3cc62eeb8270b"
metafile = true

[[files]]
file = "mods/alexs-mobs.pw.toml"
hash = "80e9d3a0247179d12b8f0c8783a91b9f998cd0884540cb1cca70ef8335a7dbce"
metafile = true

[[files]]
file = "mods/aquamirae.pw.toml"
hash = "010eff45124d5e33879af14abc9967f6498bc59be0ad36e7fa67d0f209817c3e"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "a7fa7c681c6bbc5d614b527c7f234153af5a54686013282ae918f8c1e41dfc23"
metafile = true

[[files]]
file = "mods/astemirlib.pw.toml"
hash = "f93d8745f4378541e5eb71041ec582be2012a7ded338462feff51657e86edf69"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "bda5e0c3a4411caabfd0590197eb0e38350ee084cbef540ee63a8a2e3ebf031e"
metafile = true

[[files]]
file = "mods/blueprint.pw.toml"
hash = "911a308fec5269d92af24863316db2091694bfd4f773c05c7fbf6e04a7baf906"
metafile = true

[[files]]
file = "mods/call-of-yucutan.pw.toml"
hash = "5b2a0913a2c8aff9b87fb364812409e1bc26c80e7edcdac63363e3911514dd7e"
metafile = true

[[files]]
file = "mods/citadel.pw.toml"
hash = "14a26e409ca05abdc1fa525bc9774625fd482c2673cb09639926ad05faa3fc47"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "1f0ad1ed71545dd138f5f1bd258a0c9e5c66dc803a924551f36a0d8573960e90"
metafile = true

[[files]]
file = "mods/corgilib.pw.toml"
hash = "91e6b349b1da698c7d49ddac58ce4ca4474472e36a687a296e6f58afc3846e3e"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "c13cf3374695e038c258949a0ad2c10eeaa8c53695038317339c52938085ed23"
metafile = true

[[files]]
file = "mods/elysium-api.pw.toml"
hash = "71b16c184d93ae876ae56b512325e1da23f0616db46044cb8153e32ad68cc49a"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "1c3414370922376bd5731d154d44e238117ea5f8cdbb26fd73af0352f4eb8e09"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "3e8ec047d22ec51e67244e2f942ab6642f4b7cd482684b8351b5c96a0365a242"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "9c6af114c9a0b1249bccba2d2af147190df62b7caceda64240e88aa824d7fbe3"
metafile = true

[[files]]
file = "mods/infinity-cave.pw.toml"
hash = "2a4f5b498248414dc22b0ad0842569cec063ca707d2e3f4b33c7fa3bdab9e939"
metafile = true

[[files]]
file = "mods/jadens-nether-expansion.pw.toml"
hash = "66ca5796fbfe5e0a9f972f654f801dec2dff80ab3e8dec4f2d593928b001b826"
metafile = true

[[files]]
file = "mods/l_enders-cataclysm.pw.toml"
hash = "ce935239030416ccc69517dc294072bf5bf4fbd9edfcf325a9c5e447e4625eb6"
metafile = true

[[files]]
file = "mods/lionfish-api.pw.toml"
hash = "3c5a36c256a0d287dd28811b8ff7b1979763a10bcfef76c0acf9d51853348792"
metafile = true

[[files]]
file = "mods/lios-overhauled-villages.pw.toml"
hash = "3c598b853ee541a9edff9ba552e10361a41f1361601dd0ac17f2843098a5dbee"
metafile = true

[[files]]
file = "mods/minecraft-comes-alive-reborn.pw.toml"
hash = "c9c8a4c5758549cabb61105a96804e36d9e818035aa6708a749de0cd88f13a72"
metafile = true

[[files]]
file = "mods/mowzies-mobs.pw.toml"
hash = "8acd498b2b252d1365f6ae8d67f7589341835cfc5c48d7a004f938f7193fa0d1"
metafile = true

[[files]]
file = "mods/obscure-api.pw.toml"
hash = "a1091935620666d06e28a945f29e39b6c779c669131a50ef9f4271d261f5de9a"
metafile = true

[[files]]
file = "mods/oh-the-biomes-weve-gone.pw.toml"
hash = "e19573db0865026499facee7c830113313e3587c4bbf97e4a982816c201fd145"
metafile = true

[[files]]
file = "mods/oh-the-trees-youll-grow.pw.toml"
hash = "c4e489ef04b534627aa8274b4ff4393361e63d0112d0091218fe9755ca9334b9"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
hash = "7f7a3dd55aee0d0d22cf4dc21012b8bc64deda8f256cec4dd4ade37ae733ea40"
metafile = true

[[files]]
file = "mods/rediscovered.pw.toml"
hash = "a0cdcba5a8376bfe59fb462d0d414078260f82cf7a78e57e1938a172f008746e"
metafile = true

[[files]]
file = "mods/ribbits.pw.toml"
hash = "72d82887f0418b0616eca84458e5ab6ebaa6cd0b789a00e3b7eab7ba3006514e"
metafile = true

[[files]]
file = "mods/rustic-engineer.pw.toml"
hash = "975f01c200d284f77b175bbeac78e355b5a2a07d36cfea19e0a04c4c7da9e324"
metafile = true

[[files]]
file = "mods/sky-lands.pw.toml"
hash = "2b816ccfd39e62db47562ad87cf4204dbaa027af770fe969b18cb0076271f113"
metafile = true

[[files]]
file = "mods/sleepy-hollows.pw.toml"
hash = "33849c3bcde1ee28699fe32a07670a1bf6573cf86639292e174aded375ce0c48"
metafile = true

[[files]]
file = "mods/structure-gel-api.pw.toml"
hash = "e482a80547c9a0ff0b59f0a96205c2eb44a58e657335959d3ce37c544b4f61a9"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "7106ab6a417c8afef785cd31822d379808e7d3e2747edc09657170cecda79ba2"
metafile = true

[[files]]
file = "mods/the-dawn-era.pw.toml"
hash = "b0d8d166d01a7abfd57d54ca0e802b291db32b4d954de4a9767b81f2dce93c67"
metafile = true

[[files]]
file = "mods/the-outer-end.pw.toml"
hash = "9e492a054739f9a70a0214581ac62542dbd66a6658458fc47a65cd04421d3dd1"
metafile = true

[[files]]
file = "mods/under-the-moon.pw.toml"
hash = "1a6dbbdf38e86716a633986168d121aca07a97827bd9f4b670fa7bef4dde8a7e"
metafile = true

[[files]]
file = "mods/wab.pw.toml"
hash = "03659558f41647ed0635506d199e5058dd0b98723aced69c2de2c3a162c26790"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "04c3949bed6512fd6508ad1426e40a617bcf62af81ff1e747d2efe610c0615e1"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
hash = "131f435091ecfc7bbb36a0727f99c17cd0fefcc61ef945ee652b9e097b173284"
metafile = true

[[files]]
file = "mods/zombies-more.pw.toml"
hash = "5915e099257a0057ba432b9dcb8ceec943a89276f394027d1c217cbc2a86ac3f"
metafile = true
