name = "Cool Pack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "101ca0644f07bbba817613a9d0f67b5ef55a4ee82c423d22b01d7e620aa3618d"

[versions]
forge = "47.4.12"
minecraft = "1.20.1"
