name = "Cool Pack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8242473f67a22018962fbe66895e303f934bec6fa59489743d71497f724c9bbc"

[versions]
forge = "47.4.12"
minecraft = "1.20.1"
