name = "Cool Pack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3911f6b632b1032b5448a6ce3f33af828a2b177a7d9c388d50c669bb4bb633a"

[versions]
forge = "47.4.12"
minecraft = "1.20.1"
