name = "Cool Pack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5517fc33043b2f028aed195b869ae09e50ca533e56f3de81cb862fb936a007aa"

[versions]
forge = "47.4.12"
minecraft = "1.20.1"
