name = "Cool Pack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "593a42dc1227838976501f9d1998307011faf007472f51c3a4d574e909817c55"

[versions]
forge = "47.4.12"
minecraft = "1.20.1"
